target := n76e003-aht10.ihx

c_src-y += n76e003.c

include Makefile.in

ifneq ($(skip-makefile),1)

NUVOPROG := ~/go/bin/nuvoprog
NUVOPROGC := nuvoprog-c

config: FORCE
	$(Q)$(MAKE) -C $(PICORTOS_SRC) O=$(PWD) n76e003_defconfig
	@ln -sfT Makefile.n76e003 Kbuild

nuvoprogc: $(target)
	$(NUVOPROGC) --program $< -v

nuvoprog: $(target)
	$(NUVOPROG) program -i $< -t n76e003 -c @config.json -v
        
PHONY += FORCE
FORCE:

.PHONY: $(PHONY)
endif
